### ISSUE TITLE
Nuxt Content v2.13.0 Seems to hang when trying to load the config file path

### ISSUE THREAD

**Issue by JessicaSachs** [windicss/windicss-webpack-plugin#42]
Hey, trying to setup WindiCSS with Nuxt content for Cypress's documentation.

I followed the setup docs on this repo as well as the ones on the [nuxt plugin](https://github.com/windicss/nuxt-windicss-module), but after cutting over, my build hangs midway through.

The project is OSS so I have a [failing branch here](https://github.com/cypress-io/cypress-documentation/tree/spike/windicss)

Steps to reproduce are:
1. `yarn`
2. `yarn start`

If you run with debug on, the last line that logs out is this one

https://github.com/windicss/windicss-webpack-plugin/blob/3c5c6b12cd1038ee20f78924697501c00b752104/src/plugin.ts#L150

**Comment by harlan-zw** [comment]
Hey @JessicaSachs  :) 

Thanks for your interest in Windi and apologies for the delay in getting back to you. 

The problem seems to be that you're running both the nuxt windi module as well as the old windi pre-processor (which is now deprecated). With the nuxt windi module you don't need to add the pre-processor. 

I've made a PR into your branch to fix that up.
